import { Car } from './types/cars';

export interface Tour {
  id: string;
  title: string;
  slug: string;
  destination: string;
  description: string;
  price: number;
  duration: string;
  image: string;
  category: string;
  included: string[];
  itinerary: { day: number; title: string; content: string }[];
}

export interface Service {
  name: string;
  images?: string[];
  description?: string;
}

export const CARS: Car[] = [
  {
    id: 'swift-dzire',
    name: 'Sedan Car (Swift Dzire)',
    slug: 'swift-dzire',
    brand: 'Maruti Suzuki',
    type: 'Sedan',
    transmission: 'Manual',
    fuel_type: 'CNG',
    seats: 5,
    price_per_day: 3600,
    images: ['/dzire.png'],
    features: ['Air Conditioning', '4+1 Seating', 'Music System', 'Spacious Boot'],
    description: 'Perfect budget-friendly sedan for business or family trips in and around Pune.',
    is_available: true,
    created_at: new Date().toISOString(),
    price_per_km: 'Rs. 12/km',
    per_day_running: '300km',
    toll_parking: 'Extra',
    capacity: '4 + 1',
    car_type: 'AC/ Non-AC'
  },
  {
    id: 'toyota-etios',
    name: 'Toyota Etios',
    slug: 'toyota-etios',
    brand: 'Toyota',
    type: 'Sedan',
    transmission: 'Manual',
    fuel_type: 'Diesel',
    seats: 5,
    price_per_day: 3600,
    images: ['/etios.png'],
    features: ['Air Conditioning', '4+1 Seating', 'Reliable Performance', 'Ample Legroom'],
    description: 'Extremely spacious and highly reliable sedan for smooth outstation rides.',
    is_available: true,
    created_at: new Date().toISOString(),
    price_per_km: 'Rs. 12/km',
    per_day_running: '300km',
    toll_parking: 'Extra',
    capacity: '4 + 1',
    car_type: 'AC/ Non-AC'
  },
  {
    id: 'suzuki-ertiga',
    name: 'Suzuki Ertiga',
    slug: 'suzuki-ertiga',
    brand: 'Maruti Suzuki',
    type: 'SUV',
    transmission: 'Manual',
    fuel_type: 'CNG',
    seats: 7,
    price_per_day: 4200,
    images: ['/ertiga.png'],
    features: ['Air Conditioning', '6+1 Seating', 'Smart Hybrid', 'Foldable Seats'],
    description: 'Comfortable and economical 7-seater perfect for family trips and weekend getaways.',
    is_available: true,
    created_at: new Date().toISOString(),
    price_per_km: 'Rs. 15/km',
    per_day_running: '300km',
    toll_parking: 'Extra',
    capacity: '6 + 1',
    car_type: 'AC/ Non-AC'
  },
  {
    id: 'mahindra-scorpio',
    name: 'Mahindra Scorpio',
    slug: 'mahindra-scorpio',
    brand: 'Mahindra',
    type: 'SUV',
    transmission: 'Manual',
    fuel_type: 'Diesel',
    seats: 7,
    price_per_day: 4800,
    images: ['/scorpio.png'],
    features: ['Powerful AC', '6+1 Seating', 'High Ground Clearance', 'Rugged Performance', 'Luggage Space'],
    description: 'Robust and high-performance SUV for smooth long highway journeys and hilly terrains.',
    is_available: true,
    created_at: new Date().toISOString(),
    price_per_km: 'Rs. 17/km',
    per_day_running: '300km',
    toll_parking: 'Extra',
    capacity: '6 + 1',
    car_type: 'AC/ Non-AC'
  },
  {
    id: 'toyota-innova',
    name: 'Toyota Innova',
    slug: 'toyota-innova',
    brand: 'Toyota',
    type: 'SUV',
    transmission: 'Manual',
    fuel_type: 'Diesel',
    seats: 8,
    price_per_day: 5400,
    images: ['/innova.png'],
    features: ['Dual Zone AC', '6+1 / 7+1 Seating', 'Robust Suspension', 'Luggage Carrier'],
    description: 'The standard of reliability and comfort for long distance group journeys.',
    is_available: true,
    created_at: new Date().toISOString(),
    price_per_km: 'Rs. 18/km',
    per_day_running: '300km',
    toll_parking: 'Extra',
    capacity: '6 + 1, 7 + 1',
    car_type: 'AC/ Non-AC'
  },
  {
    id: 'toyota-innova-crysta',
    name: 'Toyota Innova Crysta',
    slug: 'toyota-innova-crysta',
    brand: 'Toyota',
    type: 'Luxury',
    transmission: 'Manual',
    fuel_type: 'Diesel',
    seats: 7,
    price_per_day: 6000,
    images: ['/innova.png'],
    features: ['Premium Captain Seats', 'Ultra-luxurious Cabin', 'Dual Zone Climate Control', '6+1 Seating'],
    description: 'Chauffeur-driven premium luxury MPV offering unparalleled comfort and style.',
    is_available: true,
    created_at: new Date().toISOString(),
    price_per_km: 'Rs. 20/km',
    per_day_running: '300km',
    toll_parking: 'Extra',
    capacity: '6 + 1',
    car_type: 'AC/ Non-AC'
  },
  {
    id: 'kia-carens',
    name: 'Kia Carens',
    slug: 'kia-carens',
    brand: 'Kia',
    type: 'SUV',
    transmission: 'Manual',
    fuel_type: 'Diesel',
    seats: 8,
    price_per_day: 4800,
    images: ['/carens.png'],
    features: ['Automatic Climate Control', 'Stylish Design', 'Premium Interiors', '6+1 / 7+1 Seating'],
    description: 'Sleek and feature-packed modern family vehicle ensuring supreme comfort.',
    is_available: true,
    created_at: new Date().toISOString(),
    price_per_km: 'Rs. 16/km',
    per_day_running: '300km',
    toll_parking: 'Extra',
    capacity: '6 + 1, 7 + 1',
    car_type: 'AC/ Non-AC'
  },
  {
    id: 'tempo-traveller',
    name: 'Tempo Traveller',
    slug: 'tempo-traveller',
    brand: 'Force Motors',
    type: 'Bus',
    transmission: 'Manual',
    fuel_type: 'Diesel',
    seats: 17,
    price_per_day: 7500,
    images: ['/tempo17.png'],
    features: ['AC & Non-AC Options', '17 Seater Layout', 'Pushback Reclining Seats', 'LCD Screen & Music', 'Luggage Carrier'],
    description: 'Perfect solution for family tours, group outings, and outstation trips.',
    is_available: true,
    created_at: new Date().toISOString(),
    price_per_km: 'Rs. 24/km (Non-AC) | Rs. 28/km (AC)',
    per_day_running: '300km',
    toll_parking: 'Extra',
    capacity: '17 + 1',
    car_type: 'Non-AC (Rs. 24/km) / AC (Rs. 28/km)'
  },
  {
    id: 'honda-city',
    name: 'Honda City',
    slug: 'honda-city',
    brand: 'Honda',
    type: 'Sedan',
    transmission: 'Manual',
    fuel_type: 'Petrol',
    seats: 5,
    price_per_day: 4200,
    images: ['/honda-city.png'],
    features: ['Automatic Climate Control', 'Leatherette Upholstery', '4+1 Seating', 'Smooth Highway Cruiser'],
    description: 'Executive luxury sedan offering unmatched comfort, quiet cabin, and premium travel experience.',
    is_available: true,
    created_at: new Date().toISOString(),
    price_per_km: 'Rs. 14/km',
    per_day_running: '300km',
    toll_parking: 'Extra',
    capacity: '4 + 1',
    car_type: 'AC'
  },
  {
    id: 'maruti-wagonr',
    name: 'Maruti WagonR',
    slug: 'maruti-wagonr',
    brand: 'Maruti Suzuki',
    type: 'Hatchback',
    transmission: 'Manual',
    fuel_type: 'CNG',
    seats: 4,
    price_per_day: 2800,
    images: ['/wagonr.png'],
    features: ['Air Conditioning', 'Tall Boy Design', 'Economical Travel', '3+1 Seating'],
    description: 'Best budget-friendly compact hatchback for quick local city travel and short errands.',
    is_available: true,
    created_at: new Date().toISOString(),
    price_per_km: 'Rs. 10/km',
    per_day_running: '300km',
    toll_parking: 'Extra',
    capacity: '3 + 1',
    car_type: 'AC/ Non-AC'
  },
  {
    id: 'toyota-fortuner',
    name: 'Toyota Fortuner',
    slug: 'toyota-fortuner',
    brand: 'Toyota',
    type: 'Luxury',
    transmission: 'Automatic',
    fuel_type: 'Diesel',
    seats: 7,
    price_per_day: 9500,
    images: ['/fortuner.png'],
    features: ['4x4 All-Wheel Drive', 'VIP Interior', '6+1 Seating', 'Ultimate Presence'],
    description: 'Flagship luxury SUV for VIP guests, corporate delegation, grand weddings, and executive travel.',
    is_available: true,
    created_at: new Date().toISOString(),
    price_per_km: 'Rs. 35/km',
    per_day_running: '300km',
    toll_parking: 'Extra',
    capacity: '6 + 1',
    car_type: 'AC'
  },
  {
    id: 'tempo-32',
    name: 'Tempo Traveller (32 Seater)',
    slug: 'tempo-32',
    brand: 'Force Motors',
    type: 'Bus',
    transmission: 'Manual',
    fuel_type: 'Diesel',
    seats: 32,
    price_per_day: 9500,
    images: ['/tempo32.png'],
    features: ['AC & Non-AC Options', '32 Reclining Seats', 'HD Music & Entertainment', 'Huge Luggage Bay'],
    description: 'Spacious 32-seater luxury coach ideal for large marriage groups, corporate outings, and pilgrimage tours.',
    is_available: true,
    created_at: new Date().toISOString(),
    price_per_km: 'Rs. 28/km (Non-AC) | Rs. 32/km (AC)',
    per_day_running: '300km',
    toll_parking: 'Extra',
    capacity: '32 + 1',
    car_type: 'Non-AC (Rs. 28/km) / AC (Rs. 32/km)'
  }
];

const SERVICES_RAW = [
  "Cab Hire Pune",
  "Corporate Cab Booking",
  "Out Station Car Rental",
  "Airport Taxi in Pune",
  "Pune to Mumbai Cab",
  "Pune to Shirdi Cab",
  "Pune to Adlabs Imagica Cab",
  "Pune to Lonavla cab",
  "Pune to Lavasa Cab",
  "Pune to Mahabaleshwar Cab",
  "Pune to Matheran Cab",
  "Pune to Satara Cab",
  "Pune to Ellora Ajanta-Verul Taxi",
  "Pune to Ashtavinayak Cab",
  "Pune to Prati Balaji Mandir Cab",
  "Pune Swaminarayan Mandir Cab",
  "Pune to Trimbakeshwar Cab",
  "Pune to Shegaon cab",
  "Pune to Tuljapur Cab",
  "Pune to Pandharpur Cab",
  "Pach Jyotirlinga Darshan",
  "One Way Taxi Service",
  "Pune to Bhimashankar Cab",
  "Pune to Nashik Cab",
  "Pune to Aurangabad Cab",
  "Pune to Kolhapur Cab",
  "Pune to Sangli Cab",
  "Pune to Nagpur cab",
  "Pune to Latur cab",
  "Pune to Harihareshwar Cab",
  "Pune to Shrivardhan Cab",
  "Pune to Ganpatipule Cab",
  "Pune to Goa Cab",
  "Pune to Alibaug cab",
  "Pune to Murud Janjira Cab",
  "Pune to Ratnagiri Cab",
  "Pune to Raigad Cab",
  "Pune to Tarkarli Cab",
  "Pune to Dapoli Cab Service",
  "Cab Booking FAQs",
  "Terms And Condition",
  "Privacy Policy",
  "Round Trip Cab Booking Pune",
  "Blog",
  "Online Cab Service Pune",
  "7 Seater Cabs on Rent in Pune",
  "Cab Service in Pune",
  "Car Hire in Pune",
  "Car Provider In Pune",
  "Innova on Rent Pune",
  "Mini Bus Hire in Pune",
  "New Ertiga on Rent in Pune",
  "Pune to Navi Mumbai Cab",
  "Sedan Car for Rent in Pune",
  "Swift Dzire on Rent in Pune",
  "Tempo Traveller On Rent Pune",
  "Wedding Car Rental Pune",
  "Innova Crysta for Outstation in Pune",
  "Kia Carens Cabs on Rent in Pune",
  "Pune Airport to Outstation Cab Fare",
  "Pune to Mumbai International Airport Cab",
  "Pune to Thane Cab",
  "Pune to Panvel Cab",
  "Pune to Konkan Darshan Cab",
  "Pune to Indore Cab",
  "Pune to Gujarat Cabs",
  "Pune to Bangalore cab",
  "Pune to Ayodhya cab",
  "Pune to Akkalkot cab",
  "Pune Airport to Shirdi cab",
  "Car Hire for Outstation Tours in Pune",
  "Pune to Panchgani Cab",
  "Pune to Jejuri Cab",
  "Innova Crysta On Rent in Pune",
  "Pune to Ahmednagar Cab",
  "Mumbai Airport to Pune Cab",
  "Maruti Ertiga On Rent in Pune",
  "Pune Airport to Mahabaleshwar Cab",
  "Pune Railway Station to Mahabaleshwar Taxi fare",
  "Pune to Devkund Waterfall Cab",
  "Pune Mumbai Cab Service"
];

const EXACT_SERVICE_CONFIG: Record<string, { images: string[]; description: string }> = {
  "Cab Hire Pune": { images: ["/fortuner.png"], description: "Premium cab hire service in Pune for local city travel, corporate meetings, and outstation trips." },
  "Corporate Cab Booking": { images: ["/honda-city.png"], description: "Professional executive car rental for corporate delegates, business meetings, and event transit in Pune." },
  "Out Station Car Rental": { images: ["/carens.png"], description: "Comfortable and safe outstation car rental with experienced drivers for long distance road trips." },
  "Airport Taxi in Pune": { images: ["/pune-airport-1.jpg", "/pune-airport-2.jpg"], description: "Punctual 24/7 airport pickup and drop cabs between Pune city and Pune International Airport." },
  "Pune to Mumbai Cab": { images: ["/marine-drive.jpg"], description: "One-way and round-trip cab service via Pune-Mumbai Express Highway with clean cars and verified drivers." },
  "Pune to Shirdi Cab": { images: ["/shirdi.jpg"], description: "Spiritual pilgrimage tour cab from Pune to Sai Baba Temple Shirdi with smooth highway travel." },
  "Pune to Adlabs Imagica Cab": { images: ["/imagica.jpg"], description: "Exciting family day-trip cab package from Pune to Adlabs Imagica theme park and water park." },
  "Pune to Lonavla cab": { images: ["/lonavala.jpg"], description: "Scenic weekend mountain getaway cab service to Lonavala and Khandala viewpoints." },
  "Pune to Lavasa Cab": { images: ["/lavasa.jpg"], description: "Relaxing road trip from Pune to the colorful lake city of Lavasa with professional chauffeur." },
  "Pune to Mahabaleshwar Cab": { images: ["/mahabaleshwar.png"], description: "Cool hill station tour cab to Mahabaleshwar and Panchgani strawberry farms and viewpoints." },
  "Pune to Matheran Cab": { images: ["/matheran.jpg"], description: "Scenic road trip cab service to Dasturi Naka Matheran eco-sensitive hill station." },
  "Pune to Satara Cab": { images: ["/hero-bg.png"], description: "Outstation cab from Pune to Satara and Kaas Pathar flower valley with top-rated drivers." },
  "Pune to Ellora Ajanta-Verul Taxi": { images: ["/ellora.jpg"], description: "Heritage sightseeing taxi to the world-famous rock-cut UNESCO Ellora and Ajanta Caves." },
  "Pune to Ashtavinayak Cab": { images: ["/ashtavinayak.jpg"], description: "Holy 8 Ganesha temple darshan package across Maharashtra in comfortable AC cabs." },
  "Pune to Prati Balaji Mandir Cab": { images: ["/balaji-1.jpg", "/balaji-2.jpg"], description: "Spiritual day tour from Pune to Prati Balaji Mandir in Ketkawale for peaceful family darshan." },
  "Pune Swaminarayan Mandir Cab": { images: ["/swaminarayan-1.jpg"], description: "Hassle-free local city cab for visiting BAPS Shri Swaminarayan Mandir in Pune." },
  "Pune to Trimbakeshwar Cab": { images: ["/trimbakeshwar.jpg"], description: "Pilgrimage tour cab from Pune to sacred Trimbakeshwar Jyotirlinga temple Nashik." },
  "Pune to Shegaon cab": { images: ["/shegaon.jpg"], description: "Safe outstation taxi service from Pune to Shri Sant Gajanan Maharaj Mandir Shegaon." },
  "Pune to Tuljapur Cab": { images: ["/balaji-3.jpg"], description: "Devotional trip from Pune to Shri Tulja Bhavani Temple in Tuljapur with experienced drivers." },
  "Pune to Pandharpur Cab": { images: ["/swaminarayan-2.jpg"], description: "Comfortable outstation cab for Vitthal-Rukmini darshan in Pandharpur." },
  "Pach Jyotirlinga Darshan": { images: ["/swaminarayan-3.jpg"], description: "Customized 5 Jyotirlinga tour package covering Trimbakeshwar, Bhimashankar, Grishneshwar, Aundha & Parli." },
  "One Way Taxi Service": { images: ["/etios.png"], description: "Affordable one-way intercity cab service from Pune without paying double-side toll or return charges." },
  "Pune to Bhimashankar Cab": { images: ["/shrivardhan-4.jpg"], description: "Nature and pilgrimage ride through Sahyadri hills to Bhimashankar Jyotirlinga sanctuary." },
  "Pune to Nashik Cab": { images: ["/shrivardhan-5.jpg"], description: "Outstation cab from Pune to Nashik for temple darshan, Sula vineyards, and Godavari ghats." },
  "Pune to Aurangabad Cab": { images: ["/pune-airport-2.jpg"], description: "Reliable cab service to Chhatrapati Sambhajinagar covering Bibi Ka Maqbara and heritage sites." },
  "Pune to Kolhapur Cab": { images: ["/pune-airport-3.jpg"], description: "Comfortable highway ride to Mahalakshmi Temple Ambabai and Rankala lake Kolhapur." },
  "Pune to Sangli Cab": { images: ["/shrivardhan-3.jpg"], description: "Outstation cab rental from Pune to Sangli and Miraj with punctual chauffeur service." },
  "Pune to Nagpur cab": { images: ["/scorpio.png"], description: "Long distance highway cab service connecting Pune with Nagpur orange city." },
  "Pune to Latur cab": { images: ["/wagonr.png"], description: "Economical outstation car rental from Pune to Latur for business and personal visits." },
  "Pune to Harihareshwar Cab": { images: ["/shrivardhan-2.jpg"], description: "Serene coastal trip cab to Harihareshwar beach temple and Konkan coastline." },
  "Pune to Shrivardhan Cab": { images: ["/shrivardhan-1.jpg"], description: "Beach vacation cab from Pune to Shrivardhan pristine white sand sea beaches." },
  "Pune to Ganpatipule Cab": { images: ["/alibaug-3.jpg"], description: "Scenic Konkan coast travel from Pune to Ganpatipule beachside Ganesh Temple." },
  "Pune to Goa Cab": { images: ["/goa.jpg"], description: "Exciting road trip cab from Pune to North and South Goa beaches with spacious luggage room." },
  "Pune to Alibaug cab": { images: ["/alibaug-1.jpg"], description: "Popular weekend beach getaway cab from Pune to Alibaug forts and seaside resorts." },
  "Pune to Murud Janjira Cab": { images: ["/murud-janjira.jpg"], description: "Coastal road trip to Murud Janjira historic marine sea fort." },
  "Pune to Ratnagiri Cab": { images: ["/alibaug-2.jpg"], description: "Outstation cab service to Ratnagiri beaches, Thibaw Palace, and Alphonso mango orchards." },
  "Pune to Raigad Cab": { images: ["/hero-raigad-bg.png"], description: "Historic fort tour cab from Pune to Fort Raigad capital of Swarajya." },
  "Pune to Tarkarli Cab": { images: ["/alibaug-4.jpg"], description: "Malvan and Tarkarli beach cab service for water sports, scuba diving, and Sindhudurg fort." },
  "Pune to Dapoli Cab Service": { images: ["/konkan.png"], description: "Konkan hill and beach destination cab service from Pune to Dapoli and Karde beach." },
  "Round Trip Cab Booking Pune": { images: ["/innova.png"], description: "Flexible round-trip outstation cab rentals with fixed km rates and driver allowance included." },
  "Online Cab Service Pune": { images: ["/dzire.png"], description: "Instant WhatsApp online cab booking in Pune for local rentals and outstation travel." },
  "7 Seater Cabs on Rent in Pune": { images: ["/ertiga.png"], description: "Rent 7-seater Ertiga & Carens Cabs in Pune for comfortable family trips." },
  "Cab Service in Pune": { images: ["/carens.png"], description: "Top-rated 24/7 cab service operator in Pune for city rides, airport transfers, and outstation trips." },
  "Car Hire in Pune": { images: ["/honda-city.png"], description: "Wide choice of luxury sedans, SUVs, and passenger buses available for hire in Pune." },
  "Car Provider In Pune": { images: ["/etios.png"], description: "Trusted car provider in Pune offering clean vehicles, punctual service, and transparent billing." },
  "Innova on Rent Pune": { images: ["/innova.png"], description: "Hire 6+1 and 7+1 Toyota Innova on rent in Pune for long distance group journeys." },
  "Mini Bus Hire in Pune": { images: ["/minibus.png"], description: "32 Seater AC and Non-AC Mini Bus rental in Pune for corporate tours and marriage events." },
  "New Ertiga on Rent in Pune": { images: ["/ertiga.png"], description: "Rent latest Maruti Ertiga Smart Hybrid cabs in Pune for budget-friendly 7-seater travel." },
  "Pune to Navi Mumbai Cab": { images: ["/marine-drive.jpg"], description: "Punctual one-way and round-trip cab drops between Pune and Navi Mumbai hubs." },
  "Sedan Car for Rent in Pune": { images: ["/dzire.png"], description: "Book Dzire and Etios sedan cars on rent in Pune at just Rs. 12 per km." },
  "Swift Dzire on Rent in Pune": { images: ["/dzire.png"], description: "Maruti Swift Dzire sedan rental in Pune for business visits and outstation tours." },
  "Tempo Traveller On Rent Pune": { images: ["/tempo17.png"], description: "17-Seater AC Tempo Traveller on rent in Pune with pushback seats and music system." },
  "Wedding Car Rental Pune": { images: ["/fortuner.png"], description: "Decorated luxury cars and Fortuner / Innova Crysta rentals for wedding processions and bride-groom transit." },
  "Innova Crysta for Outstation in Pune": { images: ["/innova.png"], description: "Chauffeur-driven Innova Crysta luxury MPV for outstation travel from Pune." },
  "Kia Carens Cabs on Rent in Pune": { images: ["/carens.png"], description: "Book Kia Carens 6+1 and 7+1 modern family cabs on rent in Pune." },
  "Pune Airport to Outstation Cab Fare": { images: ["/pune-airport-2.jpg"], description: "Direct outstation cab booking straight from Pune Airport arrival terminal." },
  "Pune to Mumbai International Airport Cab": { images: ["/pune-airport-1.jpg"], description: "Timed airport transfer cabs connecting Pune directly with Mumbai T2 International Airport." },
  "Pune to Thane Cab": { images: ["/marine-drive.jpg"], description: "Direct cab service from Pune to Thane city and Ghodbunder road." },
  "Pune to Panvel Cab": { images: ["/marine-drive.jpg"], description: "Fast intercity cab drop between Pune and Panvel railway junction." },
  "Pune to Konkan Darshan Cab": { images: ["/konkan.png"], description: "Complete Konkan Darshan tour package covering beaches, forts, and temples." },
  "Pune to Indore Cab": { images: ["/scorpio.png"], description: "Comfortable interstate highway cab travel from Pune to Indore MP." },
  "Pune to Gujarat Cabs": { images: ["/fortuner.png"], description: "Interstate cab trip from Pune to Gujarat covering Surat, Vadodara, and Ahmedabad." },
  "Pune to Bangalore cab": { images: ["/honda-city.png"], description: "Long-haul outstation cab service connecting Pune with Bangalore." },
  "Pune to Ayodhya cab": { images: ["/shirdi.jpg"], description: "Pilgrimage tour cab from Pune to Shri Ram Janmabhoomi Ayodhya." },
  "Pune to Akkalkot cab": { images: ["/balaji-1.jpg"], description: "Devotional trip from Pune to Swami Samarth Maharaj Temple Akkalkot." },
  "Pune Airport to Shirdi cab": { images: ["/shirdi.jpg"], description: "Direct cab pickup from Pune Airport straight to Shirdi Sai Baba Temple." },
  "Car Hire for Outstation Tours in Pune": { images: ["/carens.png"], description: "Customized outstation tour packages with dedicated driver for multi-day trips." },
  "Pune to Panchgani Cab": { images: ["/mahabaleshwar.png"], description: "Hill station cab trip to Panchgani Table Land and Sydney point." },
  "Pune to Jejuri Cab": { images: ["/jejuri.jpg"], description: "Devotional day trip to Khandoba temple Jejuri famous for yellow turmeric celebration." },
  "Innova Crysta On Rent in Pune": { images: ["/innova.png"], description: "Premium luxury Innova Crysta rental for VIP comfort and family vacations." },
  "Pune to Ahmednagar Cab": { images: ["/scorpio.png"], description: "Intercity cab service between Pune and Ahmednagar city." },
  "Mumbai Airport to Pune Cab": { images: ["/pune-airport-3.jpg"], description: "24/7 pickup from Mumbai International & Domestic Airport terminal to Pune." },
  "Maruti Ertiga On Rent in Pune": { images: ["/ertiga.png"], description: "Ertiga 6+1 AC car rental in Pune at transparent Rs. 15 per km rate." },
  "Pune Airport to Mahabaleshwar Cab": { images: ["/mahabaleshwar.png"], description: "Direct tourist cab transfer from Pune Airport to Mahabaleshwar hill station." },
  "Pune Railway Station to Mahabaleshwar Taxi fare": { images: ["/mahabaleshwar.png"], description: "Convenient pickup from Pune Railway Station (PUNE) directly to Mahabaleshwar hotels." },
  "Pune to Devkund Waterfall Cab": { images: ["/lonavala.jpg"], description: "Trekking and waterfall adventure trip cab from Pune to Devkund." },
  "Pune Mumbai Cab Service": { images: ["/marine-drive.jpg"], description: "Reliable daily commuter cab service between Pune and Mumbai." }
};

export const SERVICES: Service[] = SERVICES_RAW
  .filter(name => name !== "Cab Booking FAQs" && name !== "Terms And Condition" && name !== "Privacy Policy" && name !== "Blog")
  .map(serviceName => {
    const custom = EXACT_SERVICE_CONFIG[serviceName];
    if (custom) {
      return {
        name: serviceName,
        images: custom.images,
        description: custom.description
      };
    }

    return {
      name: serviceName,
      images: ["/fortuner.png"],
      description: "Premium chauffeur-driven cab service in Pune with well-maintained fleet and transparent pricing."
    };
  });

// Let's also create structured Tours for our major/popular packages so they can be viewed on detail pages
export const TOURS: Tour[] = [];
